//! Browser mirror of `thinfer-conformance/tests/native.rs`. Same registry, same
//! committed fixtures (via `include_bytes!`), WebGPU instead of native wgpu.
//!
//! Driven by `wasm-bindgen-test-runner` (configured workspace-wide via
//! `.cargo/config.toml`). Fixtures are regenerated by the native conformance
//! test; CI runs that first and then this.

#![cfg(target_arch = "wasm32")]

use safetensors::SafeTensors;
use std::collections::BTreeMap;
use thinfer_core::backend::WgpuBackend;
use thinfer_core::conformance::{Dtype, OpTestContext, TestCase, diff_max_abs, registry, tol};
use wasm_bindgen_test::*;

wasm_bindgen_test_configure!(run_in_browser);

const FP32_BYTES: &[u8] = include_bytes!("../../thinfer-conformance/fixtures/fp32.safetensors");
const BF16W_BYTES: &[u8] = include_bytes!("../../thinfer-conformance/fixtures/bf16w.safetensors");

fn fixture_bytes(d: Dtype) -> &'static [u8] {
    match d {
        Dtype::Fp32 => FP32_BYTES,
        Dtype::Bf16Writes => BF16W_BYTES,
    }
}

#[wasm_bindgen_test]
async fn ops_match_pytorch_reference() {
    console_error_panic_hook::set_once();

    let backend = WgpuBackend::new()
        .await
        .expect("wgpu adapter unavailable in browser");

    let registry = registry();
    let by_op: Vec<(&'static [Dtype], Vec<TestCase>)> = registry
        .iter()
        .map(|op| (op.dtypes(), op.test_cases()))
        .collect();

    let mut by_dtype: BTreeMap<Dtype, &'static [u8]> = BTreeMap::new();
    for (dtypes, _) in &by_op {
        for &d in *dtypes {
            by_dtype.entry(d).or_insert_with(|| fixture_bytes(d));
        }
    }

    let mut failures: Vec<String> = Vec::new();
    for (op, (dtypes, cases)) in registry.iter().zip(&by_op) {
        for case in cases {
            for &dtype in *dtypes {
                let bytes = by_dtype[&dtype];
                let st = SafeTensors::deserialize(bytes).expect("safetensors parse");
                let ctx = OpTestContext {
                    backend: &backend,
                    st: &st,
                    case,
                    dtype,
                };
                let got = op.run_test(&ctx).await;
                let key = format!("{}/out", case.name);
                let expected = st
                    .tensor(&key)
                    .unwrap_or_else(|e| panic!("missing {key}: {e}"))
                    .data();
                let max_abs = diff_max_abs(dtype, &got, expected);
                let limit = tol(dtype);
                if max_abs > limit {
                    failures.push(format!(
                        "{}.{}: max abs {:.3e} > tol {:.0e}",
                        case.name,
                        dtype.as_str(),
                        max_abs,
                        limit
                    ));
                }
            }
        }
    }

    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
